### ISSUE TITLE
missing 'rank'

### ISSUE THREAD

**Issue by yemaozi88** [cjerry1243/TransferLearning-CLVC#5]
Dear cjerry, thank you for sharing your great work! 
When I executed `python train.py -c config_24k.json`, I got: 

```
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'",)
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    train(**train_config)
  File "train.py", line 74, in train
    if rank == 0:
NameError: name 'rank' is not defined

```
Is it maybe possible that the argument rank is missing in the function train in train.py?

**Comment by cjerry1243** [comment]
Yes you can remove all the rank checks in the train.py.
